verbose: 0
logger:
  classname: salina.logger.TFLogger
  log_dir: ./data/save
  cache_size: 10000
  every_n_seconds: 1
  verbose: False

algorithm:
  max_epochs: 100
  population_size: 20
  num_timesteps: 16
  train_budget: 1000
  stochasticity_seed: 100
  number_environments: 8
  neural_network:
    hidden_layer_sizes: [24, 36]
  mutation_rate: 0.2
  pbt_portion: 0.2
  discount_factor: 0.95
  hyperparameters:
    entropy_coef:
      min: 0.0001
      max: 0.1
    critic_coef:
      min: 0.5
      max: 1.5
    a2c_coef:
      min: 0.01
      max: 0.6

env:
  classname: pbt.make_env
  env_name: CartPoleContinuous-v1
  max_episode_steps: 500

optimizer:
  classname: torch.optim.Adam
  lr: 0.01