verbose: 0
logger:
  classname: salina.logger.TFLogger
  log_dir: ./data/save
  cache_size: 10000
  every_n_seconds: 1
  verbose: False

algorithm:
  max_epochs: 2000
  population_size: 40
  num_timesteps: 16
  train_budget: 1000
  stochasticity_seed: 123
  number_environments: 8
  neural_network:
    hidden_layer_sizes: [24, 36]
  mutation_rate: 0.2
  pbt_portion: 0.2
  discount_factor: 0.95
  hyperparameters:
    entropy_coef:
      min: 0.001
      max: 0.0011
    critic_coef:
      min: 1.0
      max: 1.01
    a2c_coef:
      min: 0.1
      max: 0.11

env:
  classname: pbt.make_env
  env_name: CartPoleContinuous-v1
  max_episode_steps: 200

optimizer:
  classname: torch.optim.Adam
  lr: 0.01