verbose: 0
logger:
  classname: salina.logger.TFLogger
  log_dir: ./data/save
  cache_size: 10000
  every_n_seconds: 1
  verbose: False

algorithm:
  max_epochs: 500
  population_size: 10
  num_timesteps: 4
  train_budget: 500
  stochasticity_seed: 100
  number_environments: 1
  neural_network:
    hidden_layer_sizes: [64, 64] # Pendulum: [64,64]; CartPoleContinuous: [25,25]
  mutation_rate: 0.2
  pbt_portion: 0.2
  discount_factor: 0.95
  gae: 0.8
  max_grad_norm: 0.5
  hyperparameters:
    entropy_coef:
      min: 1.0e-8
      max: 0.05
    critic_coef:
      min: 0.2
      max: 0.8
    a2c_coef:
      min: 0.5
      max: 1.5

env:
  classname: env.make_gym_env
  env_name: Pendulum-v1

optimizer:
  classname: torch.optim.Adam
  lr: 0.01