verbose: 0
logger:
  classname: salina.logger.TFLogger
  log_dir: ./tmp
  cache_size: 10000
  every_n_seconds: 10
  verbose: False

algorithm:
  max_epochs: 50
  population_size: 30
  num_timesteps: 16
  train_budget: 1000
  stochasticity_seed: 123
  number_environments: 8
  neural_network:
    hidden_layer_sizes: [24, 36]
  mutation_rate: 0.2
  pbt_portion: 0.2
  discount_factor: 0.95
  hyperparameters:
    entropy_coef:
      min: 0.0
      max: 0.01
    critic_coef:
      min: 0.5
      max: 1.5
    a2c_coef:
      min: 0.0
      max: 0.25

env:
  classname: pbt.make_env
  env_name: CartPoleContinuous-v1
  max_episode_steps: 200

optimizer:
  classname: torch.optim.Adam
  lr: 0.01